import Head from "next/head";
import GetChuckData from "../components/GetChuckData";
import GetDataAndPrint from "../components/getDataAndPrint";
import Tasks from "../components/task";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oppgave 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Oppgave 1</h1>
        <p className={styles.description}>Next.js og API</p>
        {/* <Tasks /> */}
        <GetDataAndPrint />
        <GetChuckData />
      </main>
    </div>
  );
}
